Repository artemkhere/let-me-guide-you, pull requests merged in 2019-07, with the labels that each got.

#6 Add a new Guide: Repeat Words
  Guides/Breathing/Playing.js
  Guides/PowerPose/Playing.js
  Guides/RepeatWords/Finished.js
  Guides/RepeatWords/Playing.js
  Guides/index.js
  SessionPlayer.js
Labels: enhancement

#9 Upgrade our project to use Expo SDK 33
  Guides/PowerPose/images/powerPoseImage.js
  app.json
  package.json
  yarn.lock
Labels: Refactor

#10 Implement Homescreen
  App.js
  HomeScreen/HomeScreen.js
  HomeScreen/package.json
  SessionPlayer/HUD.js
  SessionPlayer/SessionData.js
  SessionPlayer/SessionPlayer.js
  package.json
  tests/__snapshots__/App.test.js.snap
  yarn-error.log
  yarn.lock
Labels: Feature

#15 Close your eyes guide
  Guides/ClosedEyes/Finished.js
  Guides/ClosedEyes/Playing.js
  Guides/index.js
  SessionPlayer/SessionData.js
Labels: Feature
